name: 'Build LaTex Document'

on:
  push:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Checks-out the repository
      - name: Checkout
        uses: actions/checkout@v4

      #Enable cache
      - uses: actions/cache@v4
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      
      # Setup tectonic
      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.14.1
      
      # Run tectonic to compile document
      - name: Compile TeX file
        run: tectonic main.tex
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF file
          path: main.pdf
          if-no-files-found: error
          retention-days: 5

      # Upload pdf file in GitHub release
      - if: ${{ github.event_name == 'release'}}
        name: Upload pdf to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: main.pdf
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "PDF compiled from source"
